name: App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python_version: ["3.10", "3.11", "3.12"]
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
        - uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install -r requirements-dev.txt
        - name: Install app as editable app
          run: |
            python -m pip install -e src
        - name: Setup local database with seed data
          run: |
            cp .env.sample .env
            python ./src/fastapi_app/setup_postgres_database.py
            python ./src/fastapi_app/setup_postgres_seeddata.py
