name: Trigger auto deployment for hcds-wv4ux2snotsdy-ca

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/hcds-wv4ux2snotsdy-ca-AutoDeployTrigger-1efbb677-b008-40b8-88b1-f2b5257ca26f.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.hcdswv4ux2snotsdyca_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.hcdswv4ux2snotsdyca_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.hcdswv4ux2snotsdyca_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: .devcontainer/Dockerfile
          registryUrl: hcdswv4ux2snotsdyregistry.azurecr.io
          registryUsername: ${{ secrets.hcdswv4ux2snotsdyca_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.hcdswv4ux2snotsdyca_REGISTRY_PASSWORD }}
          containerAppName: hcds-wv4ux2snotsdy-ca
          resourceGroup: HCDS-rg
          imageToBuild: hcdswv4ux2snotsdyregistry.azurecr.io/hcds-wv4ux2snotsdy-ca:${{ github.sha }}
