name: Trigger auto deployment for sidhcds-xck5onkrdtz-ca

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/sidhcds-xck5onkrdtz-ca-AutoDeployTrigger-1efbb677-b008-40b8-88b1-f2b5257ca26f.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: .devcontainer/Dockerfile
          registryUrl: sidhcdsxck5onkrdtzderegistry.azurecr.io
          registryUsername: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_PASSWORD }}
          containerAppName: sidhcds-xck5onkrdtz-ca
          resourceGroup: SidHcds-rg
          imageToBuild: sidhcdsxck5onkrdtzderegistry.azurecr.io/sidhcds-xck5onkrdtz-ca:${{ github.sha }}
